sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t hafiz/docker-react-training:travis

script:
  - docker run hafiz/docker-react-training:travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-147423675398"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
