sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t hafiz/docker-react-training:travis

script:
  - docker run hafiz/docker-react-training:travis npm run test -- --coverage
